# Generated by Django 5.0 on 2023-12-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('discription', models.TextField()),
                ('img', models.FileField(upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
    ]
