# Generated by Django 5.0 on 2023-12-17 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_i',
            old_name='discription',
            new_name='Discription',
        ),
        migrations.RenameField(
            model_name='menu_i',
            old_name='img',
            new_name='Img',
        ),
        migrations.RenameField(
            model_name='menu_i',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='menu_i',
            old_name='price',
            new_name='Price',
        ),
    ]
