# Generated by Django 5.0 on 2023-12-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_discription_menu_i_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_i',
            name='Name',
            field=models.CharField(max_length=90),
        ),
    ]
