# Generated by Django 5.0 on 2023-12-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menu_i_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_i',
            name='Img',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
