# Generated by Django 5.0 on 2023-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_menu_i_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_i',
            name='Img',
            field=models.FileField(upload_to='menu/static'),
        ),
    ]
